# Generated by Django 3.0.5 on 2020-04-24 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_auto_20200423_0828'),
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('name', models.CharField(max_length=255, primary_key=True, serialize=False)),
            ],
        ),
    ]
