# Generated by Django 3.0.5 on 2020-04-24 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_destination'),
    ]

    operations = [
        migrations.AddField(
            model_name='connection',
            name='authorized_destinations',
            field=models.ManyToManyField(to='webapp.Destination'),
        ),
    ]
